### ISSUE TITLE
Warn deprecation in README

### ISSUE THREAD

**Issue by teamdandelion** [googlearchive/more-routing#78]
Rob Dodson told me this is deprecated. So the README should probably say that.

**Comment by ThomasShaped** [comment]
I'm pretty sure this will be officially deprecated when the carbon elements are released. Hopefully that shouldn't be long!

**Comment by neonsoftware** [comment]
Thanks for the Heads Up guys !

**Comment by ThomasShaped** [comment]
For a sneaky peek check out the [Lab Elements Router](https://github.com/PolymerLabs/lab-elements/blob/master/lab-router.html) 😉The carbon router was used in the [app-layout](https://github.com/PolymerLabs/app-layout) demo and was recently changed to use the lab elements version instead so we can _assume_ that this is what will soon be the carbon router.

**Comment by devinivy** [comment]
Thanks for the heads up, @danmane!  And good snooping, @ThomasShaped.

**Comment by addyosmani** [comment]
CC @tjsavage

**Comment by tjsavage** [comment]
Added a notice to the repo, thanks!
